dist: xenial
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python3 --version
  - pip3 install --upgrade pip
install:
  - pip3 install --upgrade pytest
script:
  - pytest tests.py
