dist: xenial
language: python
python:
  - "3.6.0"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

before_install:
    - python3 -m pip install -U pip

install:
  - pip3 install -r requirements-test.txt

script: pytest

after_success:
  - codecov
