dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
    - python3 -m pip install -U pip

install:
  - python3 -m pip install -U pip
  - pip3 install -r requirements-test.txt

after_success:
  - pytest --cov
script: pytest
