dist: xenial
language: python
python:
  - "3.4.0"
  - "3.6.1"
  - "nightly"

before_install:
    - python3 -m pip install -U pip

install:
  - pip3 install -r requirements-test.txt

script: pytest

after_success:
  - codecov
