#!/usr/bin/env python
from argparse import ArgumentParser
from sys import platform
import caesium

parser = ArgumentParser(prog=caesium.__program__)
group = parser.add_mutually_exclusive_group()
group.add_argument(
    "-v",
    "--version",
    action="store_true",
    help="Print %(prog)s's version number."
)
group.add_argument(
    "-e",
    "--expr",
    default="",
    help="Print the result of %(dest)s and exit."
)

args = parser.parse_args()

if args.version:
    print("%s v%s" % (caesium.__program__, caesium.__version__))
elif args.expr:
    print(caesium.run_code(args.expr))
else:
    print(
        '%s v%s running on %s.\nPress Ctrl+C or enter "exit" to exit.'
        % (caesium.__program__, caesium.__version__, platform)
    )
    while True:
        try:
            print(caesium.run_code(input("Cs> ")))
        except KeyboardInterrupt:
            break
